name: social_instagram
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <=3.0.5'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  animated_splash_screen: ^1.3.0
  lottie: ^2.0.0
  hive_flutter: ^1.1.0
  photo_view: ^0.14.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.0
  firebase_auth: ^4.7.1
  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.2
  flutter_spinkit: ^5.1.0
  multi_image_picker2: ^5.0.2
  image_picker: ^0.8.6+1
  rxdart: ^0.27.2
  dio: ^4.0.6
  intl: ^0.17.0
  comment_box: ^0.0.18
  font_awesome_flutter: ^10.4.0
  awesome_snackbar_content: ^0.1.1
  json_annotation: ^4.7.0
  url_launcher: ^6.1.7
  flutter_staggered_grid_view: ^0.6.2
  image_gallery_saver: ^2.0.3
  overlay_support: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icon/
  - assets/locales/
  - assets/json/
